bulk.update.stages <- function(data){
  ## A
  data[which(data == "Albio-Aptian")] <- "Albian-Aptian"
  data[which(data == "Ashgillian")] <- "Katian"
  data[which(data == "Auversian")] <- "Bartonian"
  data[which(data == "Acadian")] <- "Emsian-Eifelian"
  data[which(data == "Actonian")] <- "Sandbian"
  data[which(data == "Albertan")] <- "Stage 4-Wuliuan"
  data[which(data == "Aldingan")] <- "Rupelian-Priabonian"
  data[which(data == "Anticostian")] <- "Katian-Rhuddanian"
  data[which(data == "Arenig")] <- "Arenigian"
  data[which(data == "Argovian")] <- "Oxfordian"
  data[which(data == "Ashbyan")] <- "Sandbian-Katian"
  data[which(data == "Albian/Cenomamian")] <- "Albian-Cenomanian"
  data[which(data == "Aptian - Albien")] <- "Aptian-Albian"
  data[which(data == "Aquitanian - Burdigalien")] <- "Aquitanian-Burdigalian"
  data[which(data == "Anversian")] <- "Langhian-Serravallian"
  data[which(data == "Astian")] <- "Zanclean-Piacenzian"
  data[which(data == "Astiense")] <- "Zanclean-Piacenzian"
  ## B
  data[which(data == "Bashkirian-Moscovien")] <- "Bashkirian-Moscovian"
  data[which(data == "Blackriveran")] <- "Blackriverian"
  data[which(data == "Borszczow")] <- "Gedinnian"
  data[which(data == "Borszczowian")] <- "Gedinnian"
  data[which(data == "Budnanian")] <- "Ludlow"
  data[which(data == "Badenian")] <- "Serravallian"
  data[which(data == "Badenian/Burdigalian")] <- "Serravallian-Burdigalian"
  data[which(data == "Balcombian")] <- "Langhian"
  data[which(data == "Barremian-Aptien")] <- "Barremian-Aptian"
  data[which(data == "Baventian")] <- "Gelasian"
  data[which(data == "Berriassian")] <- "Berriasian"
  data[which(data == "Bolderian")] <- "Burdigalian-Serravallian"
  data[which(data == "Bruxelian")] <- "Lutetian"
  data[which(data == "Bruxellian")] <- "Lutetian"
  ## C
  data[which(data == "Chibanian-late")] <- "Chibanian"
  data[which(data == "Coniacian-Santonian-early Campanian")] <- "Coniacian-Campanian"
  data[which(data == "Capay")] <- "Lutetian-Bartonian"
  data[which(data == "Caradoc")] <- "Sandbian-Katian"
  data[which(data == "Champlainian")] <- "Chazyan-Mohawkian"
  data[which(data == "Charmouthian")] <- "Pliensbachian"
  data[which(data == "Chatfieldian")] <- "Mohawkian"
  data[which(data == "Clintonian")] <- "Aeronian-Pridoli"
  data[which(data == "Coblencian")] <- "Emsian-Lochkovian"
  data[which(data == "Coniacian-Santonien")] <- "Coniacian-Santonian"
  data[which(data == "Couvinian")] <- "Eifelian"
  data[which(data == "Croixan")] <- "Dresbachian-Trempealeauan"
  data[which(data == "Czortkow")] <- "Gedinnian"
  data[which(data == "Campanian-Maastrichtien")] <- "Campanian-Maastrichtian"
  data[which(data == "Canadian")] <- "Tremadocian-Sandbian"
  data[which(data == "Caradocian")] <- "Sandbian-Katian"
  data[which(data == "Carixian")] <- "Pliensbachian"
  data[which(data == "Cazenovian")] <- "Givetian-Eifelian"
  data[which(data == "Cerithian")] <- "Serravallian"
  data[which(data == "Chautauquan")] <- "Chatauquan"
  data[which(data == "Cincinnatian")] <- "Katian-Hirnantian"
  data[which(data == "Claibornian")] <- "Lutetian-Bartonian"
  data[which(data == "Coblenzian")] <- "Emsian-Lochkovian"
  data[which(data == "Comanchean")] <- "Albian"
  data[which(data == "Coniacian-Turonien")] <- "Coniacian-Turonian"
  data[which(data == "Corallian")] <- "Oxfordian"
  data[which(data == "Cuisian")] <- "Ypresian"
  data[which(data == "Cuisian/Lutetian")] <- "Ypresian-Lutetian"
  data[which(data == "Cuisien")] <- "Ypresian"
  ## D
  data[which(data == "Desmonesian")] <- "Desmoinesian"
  data[which(data == "Diestian")] <- "Zanclean"
  data[which(data == "Dinantian")] <- "Tournaisian-Visean"
  data[which(data == "Djulfian")] <- "Wuchiapingian"
  data[which(data == "Djulfian (Dzhulfian)")] <- "Wuchiapingian"
  data[which(data == "Domerian")] <- "Pliensbachian"
  data[which(data == "Domerianse")] <- "Pliensbachian"
  data[which(data == "Dzhulfian?")] <- "Wuchiapingian"
  data[which(data == "Dordonian")] <- "Maastrichtian"
  data[which(data == "Duntronian")] <- "Duntroonian"
  ## E
  data[which(data == "Eifelian-Famennien")] <- "Eifelian-Famennian"
  data[which(data == "Eifelian-Frasnien")] <- "Eifelian-Frasnian"
  data[which(data == "Eifelian-Givetien")] <- "Eifelian-Givetian"
  data[which(data == "Eifeliian?")] <- "Eifelian"
  data[which(data == "Ellenburger")] <- "Tremadocian"
  data[which(data == "Emsian-Eifelien")] <- "Emsian-Eifelian"
  data[which(data == "Euronian")] <- "Calabrian"
  data[which(data == "Early-Pleistocene")] <- "Early Pleistocene"
  data[which(data == "Eemian")] <- "Late Pleistocene"
  data[which(data == "Egerian")] <- "Chattian-Aquitanian"
  data[which(data == "Eggenburgian")] <- "Burdigalian"
  data[which(data == "early Middle Miocene")] <- "Middle Miocene"
  data[which(data == "Early Pleisocene")] <- "Pleistocene"
  data[which(data == "Eutyrrhenian")] <- "Late Pleistocene"
  data[which(data == "Emsian-Lockhovian")] <- "Emsian-Lochkovian"
  ## F
  data[which(data == "Falunian")] <- "Langhian"
  data[which(data == "Fuvelian")] <- "Campanian"
  data[which(data == "Famennian-Tournaisien")] <- "Famennian-Tournaisian"
  ## G
  data[which(data == "Gearyan")] <- "Wolfcampian"
  data[which(data == "Gothlandian")] <- "Silurian"
  data[which(data == "Gramian")] <- "Serravallian-Messinian"
  data[which(data == "Graysian")] <- "Serravallian-Messinian"
  data[which(data == "Gulfian")] <- "Late Cretaceous"
  data[which(data == "Gulfian?")] <- "Late Cretaceous"
  data[which(data == "Georgian")] <- "Dyeran"
  data[which(data == "Givetian-Frasnien")] <- "Givetian-Frasnian"
  ## H
  data[which(data == "Hallian")] <- "Calabrian-Chibanian"
  data[which(data == "Hamiltonian")] <- "Eifelian-Givetian"
  data[which(data == "Hamilton Sh")] <- "Eifelian-Eifelian"
  data[which(data == "Hautero-Barremian")] <- "Hauterivian-Barremian"
  data[which(data == "Headonian")] <- "Priabonian-Rupelian"
  data[which(data == "Helderbergian")] <- "Pridoli-Emsian"
  data[which(data == "Helvetian")] <- "Burdigalian"
  data[which(data == "Hemmoorian")] <- "Burdigalian-Langhian"
  data[which(data == "Homerian (Wenlock)")] <- "Homerian"
  data[which(data == "Harnagian")] <- "Rocklandian"
  data[which(data == "Helderberg")] <- "Pridoli-Emsian"
  ## I
  data[which(data == "Ionian")] <- "Chibanian-Late Pleistocene"
  data[which(data == "Ibexian")] <- "Kirkfield-Richmondian"
  ## J
  data[which(data == "Jacksonian")] <- "Bartonian-Priabonian"
  data[which(data == "Janjukian")] <- "Rupelian-Chattian"
  data[which(data == "Juanian")] <- "Chattian-Aquitanian"
  ## K
  data[which(data == "Kazanian")] <- "Roadian"
  data[which(data == "Kirkfieldian")] <- "Kirkfield"
  ## L
  data[which(data == "late Eocene")] <- "Late Eocene"
  data[which(data == "Lower Cuisian")] <- "Ypresian"
  data[which(data == "L. Asghillian (Kralodvorian)")] <- "Katian"
  data[which(data == "L. Ashgillian (Berounian)")] <- "Katian"
  data[which(data == "L. Ashgillian (Kralodvorian)")] <- "Katian"
  data[which(data == "L. Darriwilian (Dobrotivian)")] <- "Darriwilian"
  data[which(data == "Langhian-Serravallien")] <- "Langhian-Serravallian"
  data[which(data == "Langsettian")] <- "Pennsylvanian"
  data[which(data == "Late-Miocene")] <- "Late Miocene"
  data[which(data == "Late-Pleistocene")] <- "Late Pleistocene"
  data[which(data == "Late(?) Oligocene")] <- "Late Oligocene"
  data[which(data == "Latorfian")] <- "Rupelian"
  data[which(data == "Lattorfian")] <- "Rupelian"
  data[which(data == "Ledian")] <- "Lutetian"
  data[which(data == "Lias")] <- "Hettangian-Toarcian"
  data[which(data == "Llandeilian")] <- "Llandeilo"
  data[which(data == "Llandoverian")] <- "Llandovery"
  data[which(data == "Longfordian")] <- "Chattian-Burdigalian"
  data[which(data == "lower Comanchean")] <- "Albian"
  data[which(data == "Lower Dogger")] <- "Middle Jurassic"
  data[which(data == "Lower Lias")] <- "Hettangian-Sinemurian"
  data[which(data == "Ludian")] <- "Late Eocene"
  data[which(data == "Ludlovian")] <- "Ludlow"
  data[which(data == "L. Lias")] <- "Hettangian-Sinemurian"
  data[which(data == "L. Neocomian")] <- "Berriasian-Valanginian"
  data[which(data == "Lias J")] <- "Hettangian-Toarcian"
  data[which(data == "Liassic")] <- "Hettangian-Toarcian"
  data[which(data == "Lochkovian-Praguien")] <- "Lochkovian-Pragian"
  data[which(data == "Longvillian")] <- "Sandbian-Katian"
  data[which(data == "Lorraine")] <- "Katian-Hirnantian"
  data[which(data == "Lotharingian")] <- "Sinemurian"
  data[which(data == "lower Middle Cambrian")] <- "Middle Cambrian"
  data[which(data == "Lusitanian")] <- "Oxfordian-Kimmeridgian"
  ## M
  data[which(data == "Maastrictian | Campanian")] <- "Maastrichtian-Campanian"
  data[which(data == "Marinesian")] <- "Bartonian"
  data[which(data == "middle Eocene")] <- "Middle Eocene"
  data[which(data == "Middle Sarmatian")] <- "Serravallian"
  data[which(data == "Middle to Late Miocene")] <- "Middle Miocene to Late Miocene"
  data[which(data == "Malm")] <- "Oxfordian-Tithonian"
  data[which(data == "Martinez")] <- "Thanetian"
  data[which(data == "Middle Dogger")] <- "Middle Jurassic"
  data[which(data == "Moclipsian")] <- "Piacenzian-Gelasian"
  data[which(data == "Montanan")] <- "Santonian-Maastrichtian"
  data[which(data == "Muschelkalk")] <- "Anisian-Ladinian"
  data[which(data == "Magnesian")] <- "Early Ordovician"
  data[which(data == "Marmorian")] <- "Llanvirnian-Llandeilo"
  data[which(data == "Marshbrookian")] <- "Sandbian"
  data[which(data == "Mayvillian")] <- "Maysvillian"
  data[which(data == "Middle Lias")] <- "Pliensbachian-Sinemurian"
  ## N
  data[which(data == "Namurian")] <- "Mississippian-Pennsylvanian"
  data[which(data == "Namurian A")] <- "Mississippian-Pennsylvanian"
  data[which(data == "Narizian")] <- "Lutetian-Priabonian"
  data[which(data == "Neocomian")] <- "Berriasian-Hauterivian"
  data[which(data == "Newportian")] <- "Aquitanian-Serravallian"
  data[which(data == "New Scotland Ls")] <- "Pridoli-Emsian"
  ## O
  data[which(data == "Olenekian (early Spathian)")] <- "Spathian"
  data[which(data == "Olenekian (Smithian)")] <- "Smithian"
  data[which(data == "OIS 5")] <- "Chibanian-Late Pleistocene"
  data[which(data == "OIS 7")] <- "Chibanian"
  data[which(data == "Onondagan")] <- "Siegenian-Eifelian"
  data[which(data == "Osagian Stage")] <- "Osagean"
  data[which(data == "Oxfordian-Kimmeridgien")] <- "Oxfordian-Kimmeridgian"
  data[which(data == "Onondagaian")] <- "Early Devonian"
  data[which(data == "Oolite")] <- "Aalenian-Bathonian"
  data[which(data == "Oriskanian")] <- "Siegenian-Emsian"
  data[which(data == "Oriskanyan")] <- "Siegenian-Emsian"
  data[which(data == "Ozarkian")] <- "Early Ordovician"
  ## P
  data[which(data == "Piacencianse")] <- "Piacenzian"
  data[which(data == "Paspotansan")] <- "Maastrichtian-Chattian"
  data[which(data == "Piacenzian (Waltonian)")] <- "Piacenzian"
  data[which(data == "Pillarian")] <- "Aquitanian-Serravallian"
  data[which(data == "Plaisancian")] <- "Kapitean-Opoitian"
  data[which(data == "Pleistocene Late")] <- "Late Pleistocene"
  data[which(data == "Pliansbachien")] <- "Pliensbachian"
  data[which(data == "Portlandian")] <- "Tithonian"
  data[which(data == "Pottsville Stage")] <- "Morrowan-Desmoinesian"
  data[which(data == "Praghian")] <- "Pragian"
  data[which(data == "Pragian to L. Eursian")] <- "Pragian-Emsian"
  data[which(data == "Pragian-Zlichovian")] <- "Pragian-Emsian"
  data[which(data == "Praguian")] <- "Pragian"
  data[which(data == "Priabonian / Jacksonian")] <- "Bartonian-Priabonian"
  data[which(data == "Pridolian")] <- "Pridoli"
  data[which(data == "Patagonian")] <- "Zanclean-Calabrian"
  data[which(data == "Pendleian")] <- "Serpukhovian"
  data[which(data == "Porkuni")] <- "Late Ordovician"
  data[which(data == "Porterfieldian")] <- "Chazyan-Blackriverian"
  data[which(data == "Praguian-Eifelien")] <- "Pragian-Eifelian"
  data[which(data == "Praguian-Emsien")] <- "Pragian-Emsian"
  data[which(data == "Praguian-Frasnien")] <- "Pragian-Frasnian"
  data[which(data == "Praguian?")] <- "Pragian"
  ## Q
  data[which(data == "Qiongzhusian")] <- "Stage 3"
  ## R
  data[which(data == "Recent")] <- "Meghalayan"
  data[which(data == "Refugian")] <- "Priabonian"
  data[which(data == "REfugian")] <- "Priabonian"
  data[which(data == "Reinbekian")] <- "Langhian-Serravallian"
  data[which(data == "Rhaet")] <- "Rhaetian"
  data[which(data == "Rhetian")] <- "Rhaetian"
  ## S
  data[which(data == "Sahelian")] <- "Late Miocene"
  data[which(data == "Sarmatian")] <- "Serravallian"
  data[which(data == "Scaldisian")] <- "Zanclean-Piacenzian"
  data[which(data == "Senonian")] <- "Coniacian-Maastrichtian"
  data[which(data == "Serravalian")] <- "Serravallian"
  data[which(data == "Sparnacian")] <- "Thanetian-Ypresian"
  data[which(data == "Stampian")] <- "Rupelian"
  data[which(data == "Stampian-Inf.")] <- "Rupelian"
  data[which(data == "Stephanian")] <- "Gzhelian-Kasimovian"
  data[which(data == "Suessonian")] <- "Danian-Ypresian"
  data[which(data == "Schoharian")] <- "Emsian"
  data[which(data == "Sequanian")] <- "Kimmeridgian"
  data[which(data == "Sheinwoodian-Homerien")] <- "Sheinwoodian-Homerian"
  data[which(data == "second stage")] <- "Stage 2"
  ## T
  data[which(data == "Tabianian")] <- "Zanclean"
  data[which(data == "Tarantian")] <- "Late Pleistocene"
  data[which(data == "Tertiary")] <- "Paleocene-Pliocene"
  data[which(data == "Thurinigian")] <- "Rhuddanian-Homerian"
  data[which(data == "Tongerian")] <- "Rupelian"
  data[which(data == "Tongrian")] <- "Rupelian"
  data[which(data == "Tournasian")] <- "Tournaisian"
  data[which(data == "Trentonian")] <- "Sandbian-Katian"
  data[which(data == "Tyrrhenian")] <- "Late Pleistocene"
  data[which(data == "Turonian, Late")] <- "Turonian"
  data[which(data == "Taghanic")] <- "Givetian"
  data[which(data == "Taghanican")] <- "Givetian"
  data[which(data == "third stage")] <- "Stage 3"
  data[which(data == "Tommotian")] <- "Dyeran"
  data[which(data == "Triassic|Early Triassic [三疊紀|三疊紀早期]")] <- "Early Triassic"
  ## U
  data[which(data == "Upper Lias")] <- "Pliensbachian-Toarcian"
  data[which(data == "upper middle Miocene")] <- "Middle Miocene"
  data[which(data == "Upper Pleistocene")] <- "Late Pleistocene"
  data[which(data == "Upper/Late Pleistocene")] <- "Late Pleistocene"
  data[which(data == "UpperPleistocene")] <- "Late Pleistocene"
  data[which(data == "Upper Sarmatian")] <- "Serravallian"
  data[which(data == "Urgonian")] <- "Hauterivian-Aptian"
  data[which(data == "Upper Eursian")] <- "Emsian"
  ## V
  data[which(data == "Vicksburgian")] <- "Rupelian-Chattian"
  data[which(data == "Vindobonian")] <- "Langhian-Tortonian"
  data[which(data == "Viseen")] <- "Visean"
  ## W
  data[which(data == "Weichselian")] <- "Late Pleistocene"
  data[which(data == "Wemmelian")] <- "Bartonian"
  data[which(data == "Westphalian")] <- "Pennsylvanian"
  data[which(data == "Westphalian A")] <- "Pennsylvanian"
  data[which(data == "Whitbian")] <- "Rhaetian-Toarcian"
  data[which(data == "White Rockian")] <- "Floian-Sandbian"
  data[which(data == "Whiterockian")] <- "Floian-Sandbian"
  data[which(data == "Woodstockian")] <- "Maastrichtian-Chattian"
  data[which(data == "Walchow")] <- "Tremadocian-Darriwilian"
  data[which(data == "Waucoban")] <- "Dyeran"
  data[which(data == "White Jura")] <- "Oxfordian-Kimmeridgian"
  data[which(data == "Wildernessian")] <- "Sandbian-Katian"
  ## Z
  data[which(data == "Zancleen")] <- "Zanclean"
  data[which(data == "Zancleense")] <- "Zanclean"
  data[which(data == "Zechstein")] <- "Lopingian"
  data[which(data == "Zemorrian")] <- "Rupelian-Aquitanian"
  ## return updated data
  return(data)
}
